spring.application.name=configserver

server.port=8888

# Use native profile
spring.profiles.active=native

# ? Corrected local folder path for Windows (use triple forward slashes)
spring.cloud.config.server.native.search-locations=file:///D:/FlightBookingSystem/flight-configs
