spring.application.name=stripepayment

server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Optional (Eureka health check, delay)
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
management.endpoints.web.exposure.include=*

stripe.secretKey = sk_test_51RBUg04F3bwaden8pDOAtT9djRa6MFOLbNOmlrvX3qUAEPQycbWB1LsDFlgLNUSnAQLyvuzvk33ECw94lcKRgNwB00i4Jfw0zS
stripe.publishableKey = pk_test_51RBUg04F3bwaden8PktvgxA9kCiEPPFlxujrY9D3YR7CefRwiNFfnDeapnP1h1yU6VFW6Py2fJuLndvTGBWcSajL001KyrUeYY